[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@openzeppelin/contracts-upgradeable/security/=lib/v2-matching/lib/v2-core/lib/openzeppelin-contracts-upgradeable/contracts/utils/",
  "@openzeppelin/contracts-upgradeable/=lib/v2-matching/lib/v2-core/lib/openzeppelin-contracts-upgradeable/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "openzeppelin/=lib/openzeppelin-contracts/contracts/",
  "@layerzerolabs/lz-evm-oapp-v2/=lib/lz-address-book/lib/LayerZero-v2/packages/layerzero-v2/evm/oapp/",
  "@layerzerolabs/lz-evm-protocol-v2/=lib/lz-address-book/lib/LayerZero-v2/packages/layerzero-v2/evm/protocol/",
  "permit2/=lib/euler-earn/lib/euler-vault-kit/lib/permit2/",
  "lyra-utils/=lib/v2-matching/lib/v2-core/lib/lyra-utils/src/"
]

# Formatting
[fmt]
ignore = ["lib/**"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
